maintainer: Mert Cobanov

pca_params:
  n_components: 224

umap_params:
  min_dist:
    - 0.01
    - 0.1
    - 0.5
  spread: 1.0
  metrics:
    - euclidean
    - l1
    - manhattan
    - chebyshev

visualize_params:
  median_threshold: 6
